import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Simulation from './components/Simulation'
import CubeSim from './components/Cubes'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='m-0 p-0'>
      <body className="bg-gradient-to-l from-[#868F96] to-[#596164] w-screen h-screen">
        {children}
        <Navbar />
      </body>
    </html>
  )
}
